Mon Aug  3 18:12:42 PDT 2020
Traceback (most recent call last):
  File "/home/rchensix/covid19_air_travel_threat_modeling/main_serial.py", line 64, in <module>
    main()
  File "/home/rchensix/covid19_air_travel_threat_modeling/main_serial.py", line 61, in main
    serial_implementation()
  File "/home/rchensix/covid19_air_travel_threat_modeling/main_serial.py", line 27, in serial_implementation
    start_mmyy='01-20', start_day=1, init_conditions=init_conditions)
  File "/home/rchensix/covid19_air_travel_threat_modeling/model.py", line 36, in __init__
    self._load_data()
  File "/home/rchensix/covid19_air_travel_threat_modeling/model.py", line 72, in _load_data
    with open('data/metropolitan_areas.json', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/metropolitan_areas.json'
Mon Aug  3 18:12:44 PDT 2020
